
import React, { useState } from 'react';
import { generateDesignBrief } from '../services/geminiService';
import { Loader2, Sparkles, Send } from 'lucide-react';

const AIConsultant: React.FC = () => {
  const [vision, setVision] = useState('');
  const [result, setResult] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!vision.trim()) return;

    setLoading(true);
    try {
      const brief = await generateDesignBrief(vision);
      setResult(brief || 'Could not generate brief. Please try again.');
    } catch (error) {
      console.error(error);
      setResult('Error generating brief. Ensure your API key is configured.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <section id="consultant" className="py-32 bg-black border-y border-zinc-900">
      <div className="container mx-auto px-6">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-zinc-900 rounded-full mb-6">
              <Sparkles size={16} className="text-zinc-400" />
              <span className="text-xs font-bold uppercase tracking-widest text-zinc-400">Design Lab</span>
            </div>
            <h2 className="text-4xl md:text-5xl font-serif font-black mb-6">AI Design Consultant</h2>
            <p className="text-zinc-500 text-lg max-w-2xl mx-auto">
              Describe your project vision below, and our Gemini-powered assistant will draft a professional creative direction for you to review with our team.
            </p>
          </div>

          <div className="bg-zinc-950 p-8 md:p-12 border border-zinc-900 rounded-2xl">
            <form onSubmit={handleSubmit} className="mb-10">
              <div className="flex flex-col gap-4">
                <label className="text-sm font-bold uppercase tracking-widest text-zinc-400">Your Vision</label>
                <div className="relative">
                  <textarea 
                    value={vision}
                    onChange={(e) => setVision(e.target.value)}
                    placeholder="e.g. I want a sleek matte black wrap for my Porsche with subtle carbon fiber accents and a modern minimalist brand logo for my tech business."
                    className="w-full bg-black border border-zinc-800 rounded-xl p-6 text-white focus:outline-none focus:border-white transition-colors min-h-[150px] resize-none"
                  />
                  <button 
                    disabled={loading || !vision.trim()}
                    className="absolute bottom-4 right-4 p-4 bg-white text-black rounded-lg hover:bg-zinc-200 disabled:bg-zinc-800 disabled:text-zinc-600 transition-all flex items-center justify-center"
                  >
                    {loading ? <Loader2 className="animate-spin" /> : <Send size={20} />}
                  </button>
                </div>
              </div>
            </form>

            {result && (
              <div className="animate-fade-in bg-zinc-900/50 p-8 rounded-xl border border-zinc-800 prose prose-invert max-w-none">
                <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
                  <Sparkles size={20} className="text-zinc-400" />
                  Your Custom Design Brief
                </h3>
                <div className="text-zinc-400 leading-relaxed whitespace-pre-wrap">
                  {result}
                </div>
                <div className="mt-8 pt-8 border-t border-zinc-800">
                  <p className="text-sm text-zinc-500 italic">
                    This brief was instantly generated by Gemini. Our human designers will use this as a starting point to craft your actual project.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
};

export default AIConsultant;
